import HomePage from "@/components/features/home-page";

// TODO: add metadata
export const metadata = {
  title: "Online files storage",
  description: "Generated by online files storage",
};

export default HomePage;